import jsPDF from "jspdf";

interface ThreatReportData {
  ip: string;
  threatLevel: string;
  threatScore: number;
  malicious: number;
  suspicious: number;
  harmless: number;
  undetected: number;
  abuseScore: number;
  totalReports: number;
  pulses: number;
  country: string;
  isp: string;
  asn: string;
}

export function generateThreatReport(data: ThreatReportData) {
  const pdf = new jsPDF();

  // Title
  pdf.setFont("helvetica", "bold");
  pdf.setFontSize(22);
  pdf.text("CyberVerse AI", 20, 20);

  pdf.setFontSize(16);
  pdf.text("Threat Intelligence Report", 20, 32);

  // Divider
  pdf.line(20, 36, 190, 36);

  // Basic Information
  pdf.setFontSize(12);
  pdf.setFont("helvetica", "normal");

  pdf.text(`IP Address: ${data.ip}`, 20, 48);
  pdf.text(`Threat Level: ${data.threatLevel}`, 20, 56);
  pdf.text(`Threat Score: ${data.threatScore}/100`, 20, 64);

  // VirusTotal
  pdf.setFont("helvetica", "bold");
  pdf.text("VirusTotal", 20, 80);

  pdf.setFont("helvetica", "normal");
  pdf.text(`Malicious: ${data.malicious}`, 25, 90);
  pdf.text(`Suspicious: ${data.suspicious}`, 25, 98);
  pdf.text(`Harmless: ${data.harmless}`, 25, 106);
  pdf.text(`Undetected: ${data.undetected}`, 25, 114);

  // AbuseIPDB
  pdf.setFont("helvetica", "bold");
  pdf.text("AbuseIPDB", 20, 130);

  pdf.setFont("helvetica", "normal");
  pdf.text(`Abuse Score: ${data.abuseScore}%`, 25, 140);
  pdf.text(`Reports: ${data.totalReports}`, 25, 148);

  // AlienVault OTX
  pdf.setFont("helvetica", "bold");
  pdf.text("AlienVault OTX", 20, 164);

  pdf.setFont("helvetica", "normal");
  pdf.text(`Threat Pulses: ${data.pulses}`, 25, 174);

  // Location
  pdf.setFont("helvetica", "bold");
  pdf.text("Location Information", 20, 190);

  pdf.setFont("helvetica", "normal");
  pdf.text(`Country: ${data.country}`, 25, 200);
  pdf.text(`ISP: ${data.isp}`, 25, 208);
  pdf.text(`ASN: ${data.asn}`, 25, 216);

  // Footer
  pdf.setFontSize(10);
  pdf.text(
    `Generated by CyberVerse AI • ${new Date().toLocaleString()}`,
    20,
    285
  );

  pdf.save(`CyberVerse_Threat_Report_${data.ip}.pdf`);
}
interface LogReportData {
  title: string;
  content: string;

  attackType: string;
  severity: string;
  riskScore: string;
  mitre: string;
  summary: string;
  recommendation: string;
}

export function generatePDF(data: LogReportData) {
  const pdf = new jsPDF();

  pdf.setFont("helvetica", "bold");
  pdf.setFontSize(22);
  pdf.text("CyberVerse AI", 20, 20);

  pdf.setFontSize(16);
  pdf.text(data.title, 20, 35);

  pdf.setFont("helvetica", "normal");
  pdf.setFontSize(11);

  const lines = pdf.splitTextToSize(data.content, 170);

  pdf.text(lines, 20, 50);

  pdf.save("CyberVerse_Log_Report.pdf");
}